# Generated by Django 2.2.7 on 2020-04-02 14:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('color_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('hex_code', models.CharField(max_length=6, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_hex_code', message="colox hex code doesn't comply.", regex='^#[A-F0-9]{6}$')])),
                ('pantone', models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_pantone', message="colox pantone doesn't comply.", regex='^\\d\\d\\-\\d{4}$')])),
            ],
        ),
    ]
